### ISSUE TITLE
How to see, if exclidraw is using this instead of main server?

### ISSUE THREAD

**Issue by pandel** [excalidraw/excalidraw-room#140]
Hi!

I tried to setup excalidraw (Docker) to use this colab server (Docker) via overlay network, but it seems as if it is totally ignoring it. I set the necessary env variables in the .env file for excalidraw, but does not seem to use them at all.

It would be nice to get a hint how to use this.

Many thanks!
Regards
Holger

**Comment by pandel** [comment]
Have to answer myself: it is not enough to provide service through overlay network, the client has to be able to access the colab service itself.

**Comment by Blakeinstein** [comment]
Well I have been looking at the readme.md and I see that

> At the moment, self-hosting your own instance doesn't support sharing or collaboration features.

so there is probably no solution to this as of now, other than to implement this yourself
