### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-room#9]

**Comment by j-f1** [comment]
Let’s make sure not to go overboard with the rules, though. We don’t want to reduce productivity in favor of chasing imaginary “clean code.“

**Comment by lipis** [comment]
We will not.. but it's not only about the imaginary clean code! Most of the things will be automated anyways.. I just want to keep things consistent across Excalidraw organization..

> _Regardless of how many people contribute, the code should always look like it was written by one person._
> 
> — Someone on the interwebs )
