### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Turakar** [excalidraw/excalidraw-room#90]
Hello,

 I tried building this project using
```bash
docker build -t excalidraw-room .
```
This works for commit 35314725c4f98df68f76698bf91c9b0c991681b1, but not for the latest master.

**Comment by Turakar** [comment]
https://github.com/excalidraw/excalidraw-room/runs/1013586346

seems to be related

**Comment by asvinours** [comment]
fixed in #109
